import { describe, it, expect } from "vitest";
import { render, screen, within } from "@testing-library/react";
import InvoiceDocument from "@/components/InvoiceDocument";
import { VALID_INVOICE } from "../fixtures";
import type { Invoice } from "@/types/invoice";

function invoiceWith(overrides: Partial<Invoice["details"]>): Invoice {
  return {
    ...VALID_INVOICE,
    details: { ...VALID_INVOICE.details, ...overrides },
  };
}

describe("InvoiceDocument", () => {
  // ─── parties ───────────────────────────────────────────────────────────────

  it("renders the sender name", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText("Acme Corp")).toBeInTheDocument();
  });

  it("renders the receiver name", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText("Client Inc")).toBeInTheDocument();
  });

  it("renders the invoice number", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText("INV-001")).toBeInTheDocument();
  });

  // ─── line items ────────────────────────────────────────────────────────────

  it("renders each line item's name", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText("Web Development")).toBeInTheDocument();
  });

  it("renders each line item's computed total", () => {
    // item: qty=10, price=100 → total=1000.00 USD
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText("1000.00 USD")).toBeInTheDocument();
  });

  it("renders the invoice subtotal", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    // formatNumberWithCommas(1000, "en-US") = "1,000.00"
    // Both subtotal and total show this value, so use *All* variant
    const elements = screen.getAllByText(/1,000\.00 USD/);
    expect(elements.length).toBeGreaterThanOrEqual(1);
  });

  // ─── total in words ────────────────────────────────────────────────────────

  it("displays the total-in-words text when includeTotalInWords is true", () => {
    render(
      <InvoiceDocument invoice={invoiceWith({ includeTotalInWords: true })} />
    );
    // "One thousand USD" is generated by formatTotalInWords
    expect(screen.getByText(/one thousand/i)).toBeInTheDocument();
  });

  it("hides the total-in-words section when includeTotalInWords is false", () => {
    render(
      <InvoiceDocument invoice={invoiceWith({ includeTotalInWords: false })} />
    );
    expect(screen.queryByText(/one thousand/i)).not.toBeInTheDocument();
  });

  // ─── conditional adjustment rows ──────────────────────────────────────────

  it("hides the discount row when discountEnabled is false", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />); // discountEnabled=false
    expect(screen.queryByText(/discount/i)).not.toBeInTheDocument();
  });

  it("shows the discount row when discountEnabled is true and amount > 0", () => {
    render(
      <InvoiceDocument
        invoice={invoiceWith({
          discountEnabled: true,
          discountDetails: { amount: 10, amountType: "percentage" },
        })}
      />
    );
    // "Discount:" label from document.discount translation
    expect(screen.getByText(/discount/i)).toBeInTheDocument();
  });

  it("hides the tax row when taxEnabled is false", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.queryByText(/^Tax:$/i)).not.toBeInTheDocument();
  });

  it("shows the tax row when taxEnabled is true and amount > 0", () => {
    render(
      <InvoiceDocument
        invoice={invoiceWith({
          taxEnabled: true,
          taxDetails: { amount: 20, amountType: "amount" },
        })}
      />
    );
    expect(screen.getByText(/^Tax:$/i)).toBeInTheDocument();
  });

  it("hides the shipping row when shippingEnabled is false", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.queryByText(/shipping/i)).not.toBeInTheDocument();
  });

  it("shows the shipping row when shippingEnabled is true and cost > 0", () => {
    render(
      <InvoiceDocument
        invoice={invoiceWith({
          shippingEnabled: true,
          shippingDetails: { cost: 50, costType: "amount" },
        })}
      />
    );
    expect(screen.getByText(/shipping/i)).toBeInTheDocument();
  });

  // ─── logo ──────────────────────────────────────────────────────────────────

  it("renders the logo image when invoiceLogo is a data URL", () => {
    const dataUrl = "data:image/png;base64,ABC";
    render(
      <InvoiceDocument invoice={invoiceWith({ invoiceLogo: dataUrl })} />
    );
    const logo = screen.getByAltText(/logo of acme corp/i);
    expect(logo).toBeInTheDocument();
    expect((logo as HTMLImageElement).src).toContain("data:image/png");
  });

  it("does not render a logo image when invoiceLogo is empty", () => {
    render(<InvoiceDocument invoice={invoiceWith({ invoiceLogo: "" })} />);
    expect(screen.queryByAltText(/logo/i)).not.toBeInTheDocument();
  });

  // ─── payment info ──────────────────────────────────────────────────────────

  it("renders bank payment information when provided", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText(/First National Bank/)).toBeInTheDocument();
  });

  // ─── additional notes & payment terms ─────────────────────────────────────

  it("renders additional notes when present", () => {
    render(<InvoiceDocument invoice={VALID_INVOICE} />);
    expect(screen.getByText("Thank you for your business!")).toBeInTheDocument();
  });

  it("does not render the additional notes section when the field is empty", () => {
    render(<InvoiceDocument invoice={invoiceWith({ additionalNotes: "" })} />);
    expect(screen.queryByText("Thank you for your business!")).not.toBeInTheDocument();
  });

  // ─── signature ─────────────────────────────────────────────────────────────

  it("renders signature image when signature data is a data URL", () => {
    const sigDataUrl = "data:image/png;base64,SIG";
    render(
      <InvoiceDocument
        invoice={invoiceWith({
          signature: { data: sigDataUrl },
        })}
      />
    );
    // The signature img renders with alt text from translation "document.signature"
    const sig = screen.queryByRole("img", { name: /signature/i });
    // Signature section renders only when isDataUrl returns true
    expect(sig).toBeInTheDocument();
  });
});
